server {
    listen 80;
    listen [::]:80;
    # Jika menggunakan port dinamis dari environment variable Railway (Opsional, pastikan envsubst aktif)
    # listen ${PORT};
    
    server_name _;
    index index.php index.html;
    
    error_log  /var/log/nginx/error.log warn;
    access_log /var/log/nginx/access.log;
    
    root /var/www/html/public;

    client_max_body_size 64M; # Batas ukuran upload file (disesuaikan untuk upload surat/lampiran)

    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        
        # Timeout tambahan agar proses agak panjang tidak 502 Bad Gateway
        fastcgi_read_timeout 300;
        fastcgi_connect_timeout 300;
        fastcgi_send_timeout 300;
    }

    # Blokir akses ke file tersembunyi (.env, .git, dll)
    location ~ /\.(?!well-known).* {
        deny all;
    }
}