server {
    # Railway akan mengganti ${PORT} ini saat container berjalan
    listen ${PORT};
    server_name _;
    
    index index.php index.html;
    root /var/www/html/public;

    error_log  /var/log/nginx/error.log warn;
    access_log /var/log/nginx/access.log;

    client_max_body_size 64M;

    # Pengaturan untuk file statis
    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }

    # Pengaturan PHP-FPM
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        
        # Timeout untuk mencegah 502 saat proses berat
        fastcgi_read_timeout 300;
        fastcgi_connect_timeout 300;
        fastcgi_send_timeout 300;
    }

    # Keamanan: Blokir akses ke file sensitif
    location ~ /\.(?!well-known).* {
        deny all;
    }

    # Keamanan tambahan: cegah akses ke file log atau konfigurasi
    location ~* \.(log|env|git|htaccess|sql)$ {
        deny all;
    }
}